version: '3.8'

services:
  app:
    build: .
    container_name: spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.YOUR_SUPABASE_REFERENCE.supabase.co:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: YOUR_SUPABASE_PASSWORD